---
apiVersion: v1
kind: Service
metadata:
  name: esp-power-on
  namespace: {{ .Release.Namespace }}
spec:
  ipFamilyPolicy: SingleStack
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app: esp-power-on
